id: I6877748A
ocr_import_info:
  timestamp: '2023-09-29T16:05:27.404019+00:00'
  batch_id: batch-9d48
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 17:04:23.873242+00:00
last_modified: 2023-09-29 17:04:23.873249+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ8044
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ8044
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྭ་སྟོད་བསྡུས་གྲྭ།
  languages:
  - bo
  author: ཤངས་པ་ཀུན་མཁྱེན་མཆོག་ལྷ་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.9858869299831364
  ocr_word_median_confidence_index: 0.9999991
bases:
  I1KG10525:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10525
      total_pages: 536
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10525.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999991
      ocr_word_mean_confidence_index: 0.9858869299831364
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
